# Generated by Django 3.1.7 on 2021-03-23 16:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersCSiswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('nama', models.TextField()),
                ('alamat', models.TextField()),
                ('no_telp', models.IntegerField()),
                ('sekolah_asal', models.TextField()),
                ('nama_ortu', models.TextField()),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Jurusan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_Jurusan', models.TextField(blank=True, null=True)),
                ('siswa_pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_csiswa.userscsiswa', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
