# Generated by Django 3.1.7 on 2021-03-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_csiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jurusan',
            old_name='nama_Jurusan',
            new_name='nama_jurusan',
        ),
    ]
