# Generated by Django 3.1.7 on 2021-03-23 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_csiswa', '0002_auto_20210323_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurusan',
            name='siswa_pemilih',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_csiswa.userscsiswa', validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)]),
        ),
    ]
