# Generated by Django 3.1.7 on 2021-03-24 03:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_csiswa', '0003_auto_20210323_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCSiswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.TextField()),
                ('alamat', models.TextField()),
                ('no_telp', models.IntegerField()),
                ('sekolah_asal', models.TextField()),
                ('nama_ortu', models.TextField()),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='jurusan',
            name='siswa_pemilih',
        ),
        migrations.AddField(
            model_name='jurusan',
            name='kuantitas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='UsersCSiswa',
        ),
        migrations.AddField(
            model_name='datacsiswa',
            name='jurusan',
            field=models.ManyToManyField(blank=True, to='users_csiswa.Jurusan'),
        ),
        migrations.AddField(
            model_name='datacsiswa',
            name='user_csiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
